### ISSUE TITLE
Invalid representation of empty CecLogicalAddresses

### ISSUE THREAD

**Issue by igorbernstein** [ssalonen/cec-rs#1]
Currently cec-rs initializes an empty CecLogicalAddresses struct as:

```rust
cec_logical_addresses {
            primary: CecLogicalAddress::Unknown as i32,
            addresses: [CecLogicalAddress::Unknown as i32; 16],
        };
```

However this differs from libcec's representation, which marks an empty list with a primary address of UNREGISTERED:
https://github.com/Pulse-Eight/libcec/blob/76551ea1dd9a55f0ce1533e440dc12dbc594f7ba/include/cectypes.h#L1280-L1285

This seems to force cec-rs to always wake up devices even if CecConnectionCfg#wakeDevices is unset.

**Comment by ssalonen** [comment]
Good catch! Would you like to post a PR?
