### ISSUE TITLE
Callbacks should be Send

### ISSUE THREAD

**Issue by igorbernstein** [ssalonen/cec-rs#3]
I'm fairly new to rust, but it seems like callbacks (ie CecConnectionCfg#command_received_callback) should require the closure to be `Send`. libcec will invoke callbacks from a different thread than the main thread that constructed CecConnectionCfg.

**Comment by ssalonen** [comment]
I think you are correct.

I checked that only `Send` should be enough, no need for `Sync`, since `libcec` ensures that only at most one callback is called at the same time
